### ISSUE TITLE
What's the 'dl1/datasets/actions/satnd'？

### ISSUE THREAD

**Issue by AnnLoya** [TianzhongSong/Dataset-maker-for-action-recognition#1]
hello, thanks for your work but i met a problem when i was running the codes. firstly i bash the download.sh, successfully, and then i try to python run_cam.py, the feedback was:
```
Traceback (most recent call last):`
  File "run_cam.py", line 20, in <module>
    os.mkdir(root_path + action)
FileNotFoundError: [Errno 2] No such file or directory: '/home/dl1/datasets/actions/satnd
```
hmmm so what's the ‘satnd' ? Did i miss anything?

**Comment by chenyeheng** [comment]
It's wrong spelling. stand

**Comment by chenyeheng** [comment]
> hello, thanks for your work but i met a problem when i was running the codes. firstly i bash the download.sh, successfully, and then i try to python run_cam.py, the feedback was:
> 
> ```
> Traceback (most recent call last):`
>   File "run_cam.py", line 20, in <module>
>     os.mkdir(root_path + action)
> FileNotFoundError: [Errno 2] No such file or directory: '/home/dl1/datasets/actions/satnd
> ```
> hmmm so what's the ‘satnd' ? Did i miss anythingIt's wrong spelling. stand

> hello, thanks for your work but i met a problem when i was running the codes. firstly i bash the download.sh, successfully, and then i try to python run_cam.py, the feedback was:
> 
> ```
> Traceback (most recent call last):`
>   File "run_cam.py", line 20, in <module>
>     os.mkdir(root_path + action)
> FileNotFoundError: [Errno 2] No such file or directory: '/home/dl1/datasets/actions/satnd
> ```
> hmmm so what's the ‘satnd' ? Did i miss anything?

It's wrong spelling. stand

**Comment by yehengchen** [comment]
> hello, thanks for your work but i met a problem when i was running the codes. firstly i bash the download.sh, successfully, and then i try to python run_cam.py, the feedback was:
> 
> ```
> Traceback (most recent call last):`
>   File "run_cam.py", line 20, in <module>
>     os.mkdir(root_path + action)
> FileNotFoundError: [Errno 2] No such file or directory: '/home/dl1/datasets/actions/satnd
> ```
> hmmm so what's the ‘satnd' ? Did i miss anything?

It's wrong spelling. *stand
